version: "3.3"

services:
  app:
    build:  .
    image: nimhans-deploy:1.0
    container_name: app-container
    depends_on:
      - db
    expose:
      - "8585"
    ports:
      - target: 8585
        published: 8585
        protocol: tcp
        mode: host

  db:
    build:  ./mysql_deploy/
    image:  mysql-docker:1.0
    container_name: db-container
    environment:
      - MYSQL_DATABASE=nimhans
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=spring
    expose:
      - "3306"
    ports:
      - target: 3306
        published: 4040
        protocol: tcp
        mode: host
    volumes:
      - ./cache:/var/lib/mysql