version: "3.3"

services:
  db:
    build:  ./mysql-deploy/
    image:  vivekmt2019137/nimhans-mysql:1.0
    restart:  always
    # container_name: db
    networks:
      - database
    environment:
      - MYSQL_DATABASE=nimhans
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=spring
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:  .
    image: vivekmt2019137/nimhans-pe:1.0
    depends_on:
      - db
    networks:
      - database
    expose:
      - "8585"
    ports:
      - "8585:8585"

volumes:
  db-data:

networks:
  database:
    driver: bridge

